name: parenting_community_wall
description: A parenting community wall app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.10.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
